# Exercises

In [68]:
import math
import numpy as np
import scipy.signal as scs
import matplotlib.pyplot as plt

## Linear Algebra

### Vectors

We have two 4D vectors
\begin{equation*}
    \vec{v} = \left(1, -2, 5, 0\right)^\mathrm{T}
    \quad\mathrm{and}\quad
    \vec{w} = \left(2, 2, 3, -1\right)^\mathrm{T}
\end{equation*}

1. Calculate the lengths $|\vec{v}|$, $|\vec{w}|$
1. Calculate the sum $\vec{v} + \vec{w}$ and difference $\vec{v} - \vec{w}$
1. Calculate the scalar product $\vec{v}\cdot \vec{w}$
1. What is angle $\phi$ in degrees between both vectors?
1. Find a vector $\vec{u}\neq \vec{0}$ which is orthogonal to $\vec{v}$


#### Exercise 1

The length of an vetor is calculated using
\begin{equation*}
    |\vec{v}| = \sqrt{\sum_{i=1}^n v_i^2}
\end{equation*}

So for the first vector we get
\begin{equation*}
    |\vec{v}| = \sqrt{1^2 + (-2)^2 + 5^2 + 0^2}
        = \sqrt{1 + 4 + 25 + 0} = \sqrt{30} \approx 5.48
\end{equation*}
and for the second one
\begin{equation*}
    |\vec{v}| = \sqrt{2^2 + 2^2 + 3^2 + (-1)^2}
        = \sqrt{4 + 4 + 9 + 1} = \sqrt{18} \approx 4.24
\end{equation*}

See cell below for the computational solution.

In [22]:
# Computational solution for vector exercise 1
v = [1, -2, 5, 0]
w = [2, 2, 3, -1]


## Using numpy
norm_v = np.linalg.norm(v)
norm_w = np.linalg.norm(w)
print("# Using numpy methods:")
print("Length of v: {:.2f}".format(norm_v))
print("Length of w: {:.2f}".format(norm_w))


## Using standard python
def vec_norm(v):
    """ Calculates the norm of given vector v, input as list """
    return math.sqrt(sum([vi**2 for vi in v]))

norm_v = vec_norm(v)
norm_w = vec_norm(w)
print("\n# Using standard methods:")
print("Length of v: {:.2f}".format(norm_v))
print("Length of w: {:.2f}".format(norm_w))

# Using numpy methods:
Length of v: 5.48
Length of w: 4.24

# Using standard methods:
Length of v: 5.48
Length of w: 4.24


#### Exercise 2

The sum is simply computed by adding each corresponding elements:
\begin{equation}
 \vec{v} + \vec{w} =
 \left(1 + 2, -2 + 2, 5 + 3, 0 - 1\right)^\mathrm{T} =
 \left(3, 0, 8, -1\right)^\mathrm{T}
\end{equation}
The same for the difference:
\begin{equation}
 \vec{v} - \vec{w} =
 \left(1 - 2, -2 - 2, 5 - 3, 0 + 1\right)^\mathrm{T} =
 \left(-1, -4, 2, 1\right)^\mathrm{T}
\end{equation}

See cell below for computational solution.

In [21]:
# Computational solution for vector exercise 2
v = [1, -2, 5, 0]
w = [2, 2, 3, -1]


## Using numpy
u1 = np.array(v) + np.array(w)
u2 = np.array(v) - np.array(w)
print("# Using numpy methods:")
print("v + w = ({})^T".format(
    ", ".join(["{:.2f}".format(ui) for ui in u1])))
print("v - w = ({})^T".format(
    ", ".join(["{:.2f}".format(ui) for ui in u2])))


# Using standard python
u1 = [vi + wi for vi, wi in zip(v, w)]
u2 = [vi - wi for vi, wi in zip(v, w)]
print("\n# Using standard methods:")
print("v + w = ({})^T".format(
    ", ".join(["{:.2f}".format(ui) for ui in u1])))
print("v - w = ({})^T".format(
    ", ".join(["{:.2f}".format(ui) for ui in u2])))

# Using numpy methods:
v + w = (3.00, 0.00, 8.00, -1.00)^T
v - w = (-1.00, -4.00, 2.00, 1.00)^T

# Using standard methods:
v + w = (3.00, 0.00, 8.00, -1.00)^T
v - w = (-1.00, -4.00, 2.00, 1.00)^T


#### Exercise 3

For the scalar product we add the products of each corresponding components
\begin{equation}
 \vec{v} \cdot \vec{w} = \sum_{i=1}^n v_i w_i
\end{equation}
and get
\begin{equation}
 \vec{v} \cdot \vec{w} =
 1 \cdot 2 + -2 \cdot 2 + 5 \cdot 3 + 0 \cdot (- 1) =
 2 - 4 + 15 +0 = 13
\end{equation}
for the example vectors.

See cell below for the computational solution.

In [20]:
# Computational solution for vector exercise 3
v = [1, -2, 5, 0]
w = [2, 2, 3, -1]


## Using numpy
a = np.dot(v, w)
print("# Using numpy methods:")
print("v * w = {:.2f}".format(a))


# Using standard python
a = sum([vi * wi for vi, wi in zip(v, w)])
print("\n# Using standard methods:")
print("v * w = {:.2f}".format(a))

# Using numpy methods:
v * w = 13.00

# Using standard methods:
v * w = 13.00


#### Exercise 4

For the angle $\phi$ we use the alternative formula
\begin{equation}
    \cos(\phi) =
    \frac{\vec{v} \cdot \vec{w}}{|\vec{v}|\,|\vec{w}|}
\end{equation}

We already computed all the ingredients (lengths and the scalar product) in the other exercises so we can reuse them here.
Using the inverse cosine we get
\begin{align}
     \cos(\phi)
     &= \arccos\left(
         \frac{\vec{v} \cdot \vec{w}}{|\vec{v}|\,|\vec{w}|}
     \right) \\
     &= \arccos\left(\frac{13}{5.48 * 4.24}\right)
     \approx \arccos(0,56) = 0,98 = 55,98°
\end{align}

See cell below for the computational solution.

In [19]:
# Computational solution for vector exercise 4
v = [1, -2, 5, 0]
w = [2, 2, 3, -1]

cos_phi = np.dot(v, w) / (np.linalg.norm(v) * np.linalg.norm(w))
phi = np.arccos(cos_phi)
phi_deg = np.rad2deg(phi)
print("The angle is {:.2f}°".format(phi_deg))

The angle is 55.98°


#### Exercise 5

To find a orthogonal vector we first note that two vectors are orthogonal when their scalar product vanishes.
Then $\cos(\phi) = 0 \rightarrow \phi = 90°$.
This problem does not have a unique solution.
To get on possible solution, we can fix 3 of the 4 unknown components of $\vec{u}$ and then solve a single equation to find the 4th one which then fullfills the requirement:
Here we simply use the 1st, 2nd and 4th component of $\vec{w}$ for $\vec{u}$ which results in the orthogonal vector
\begin{align}
    \vec{v}\cdot\vec{u} \overset{!}{=} 0 &=
    1 \cdot 2 + -2 \cdot 2 + 5 \cdot u_3 + 0 \cdot -1 \\
    u_3 &= \frac{2}{-5} + \frac{-4}{-5}
    = \frac{2}{5}
\end{align}

Alternatively we could also have noted that the 4th component of $\vec{v}$ is $0$, so any vector of the form $(0, 0, 0, u_4)^\mathrm{T}$ is automatically orthogonal to $\vec{v}$.

See cell below for the computational solution.

In [27]:
# Computational solution for vector exercise 5
# Here we just prove we found an orthogonal vector,
# because an actual computation is more complicated
v = [1, -2, 5, 0]
u = [2, 2, 2. / 5., -1]

cos_phi = np.dot(v, u) / (np.linalg.norm(v) * np.linalg.norm(u))
phi = np.arccos(cos_phi)
phi_deg = np.rad2deg(phi)
print("The angle is {:.2f}°".format(phi_deg))

The angle is 90.00°


### Matrices

1. We have 2 matrices $\underline{A}, \underline{B}$
  and a vector $\vec{v}$
  \begin{equation*}
    \underline{A} =
      \begin{pmatrix} 1 & 2 & 3 \\ 3 & 2 & 1 \end{pmatrix}
    \,\mathrm{, }\quad
    \underline{B} =
      \begin{pmatrix} 0 & 2 \\ 1 & -1 \\ 0 & 1 \end{pmatrix}
    \,\mathrm{, }\quad
    \vec{v} = \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}
  \end{equation*}
  Calculate $\underline{A}\,\underline{B}$,
  $\underline{B}\,\underline{A}$,
  $\underline{A}\,\vec{v}$ and $\vec{v}^\mathrm{T}\,\underline{B}$.
1. Calculate the inverses (if existing) of
  \begin{equation*}
    \underline{A} =
      \begin{pmatrix} 1 & 2 \\ 4 & 2 \end{pmatrix}
    \quad\mathrm{, }\quad
    \underline{B} =
      \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}
  \end{equation*}
1. We have a matrix $\underline{M} = \underline{1}$
  and a vector $\vec{v}^\mathrm{T} = \left(v_1, v_2, v_3\right)$.
  Calculate
  \begin{equation*}
    \vec{v}^\mathrm{T}\, \underline{M}\, \vec{v}
  \end{equation*}

#### Exercise 1

We only calculate $\underline{A}\,\underline{B}$ explicitely here, the rest is done in code.
\begin{align}
    \underline{A}\,\underline{B} &=
    \begin{pmatrix} 
        1 & 2 & 3 \\ 3 & 2 & 1 \end{pmatrix}_{2,3}
    \begin{pmatrix}
        0 & 2 \\ 1 & -1 \\ 0 & 1 \end{pmatrix}_{3, 2} \\
    &=
    \begin{pmatrix}
        1 \cdot 0 + 2 \cdot 1 + 3 \cdot 0 &
        1 \cdot 2 + 2 \cdot -1 + 3 \cdot 1 \\
        3 \cdot 0 + 2 \cdot 1 + 1 \cdot 0 &
        3 \cdot 2 + 2 \cdot -1 + 1 \cdot 1
    \end{pmatrix}_{2,2} = 
    \begin{pmatrix}
        2 & 3 \\ 2 & 5
    \end{pmatrix}_{2,2}
\end{align}

See cell below for the computational solution.

In [42]:
# Computational solution for matrix exercise 1
A = [[1, 2, 3], [3, 2, 1]]  # row-wise definition as in C
B = [[0, 2], [1, -1], [0, 1]]
v = np.array([[4], [5], [6]])  # Using an explicit column vector

AB = np.matmul(A, B)
BA = np.matmul(B, A)
Av = np.matmul(A, v)
vB = np.matmul(v.T, B)
dimAB = AB.shape
dimBA = BA.shape
dimAv = Av.shape
dimvB = vB.shape

print("AB =\n{}".format(AB))
print("  Dimensions: {}".format(dimAB))
print("\nBA =\n{}".format(BA))
print("  Dimensions: {}".format(dimBA))
print("\nAv =\n{}".format(Av))
print("  Dimensions: {}".format(dimAv))
print("\nvB = {}".format(vB))
print("  Dimensions: {}".format(dimvB))

AB =
[[2 3]
 [2 5]]
  Dimensions: (2, 2)

BA =
[[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]
  Dimensions: (3, 3)

Av =
[[32]
 [28]]
  Dimensions: (2, 1)

vB = [[5 9]]
  Dimensions: (1, 2)


#### Exercise 2

For these $(2,2)$ matrices we can use the explicit formula for the inverse
\begin{equation}
  \underline{A}^{-1} =
  \frac{1}{1 \cdot 2 - 4 \cdot 2}
  \begin{pmatrix}2 & -2 \\ -4 & 1\end{pmatrix} =
  \begin{pmatrix}
      -\frac{1}{3} & \frac{1}{3} \\
      \frac{2}{3} & -\frac{1}{6}
  \end{pmatrix}
\end{equation}

The inverse of $\underline{B}$ does not exist, because both rows are multiples of each other.
This mean it has not full rank or one of its eigenvalues is $0$ or the denominator of the factor for the inverse computation ("determinant") is zero
\begin{equation}
  \frac{1}{1 \cdot 4 - 2 \cdot 2} = \frac{1}{0}
\end{equation}

See cell below for the computational solution.

In [55]:
# Computational solution for matrix exercise 2
A = [[1, 2], [4, 2]]
B = [[1, 2], [2, 4]]

Ainv = np.linalg.inv(A)
test1 = np.matmul(Ainv, A)
test2 = np.matmul(A, Ainv)
print("Ainv =\n{}".format(Ainv))
print("  Dimensions: {}".format(Ainv.shape))
print("Test if Ainv * A is identity:")
print("  Ainv * A =\n{}".format(test1))
print("  A * Ainv =\n{}".format(test2))

# This will fail
try:
    Binv = np.linalg.inv(B)
except np.linalg.LinAlgError as err:
    print("\nCalculation of inverse of B failed, reason: ", err)

Ainv =
[[-0.33333333  0.33333333]
 [ 0.66666667 -0.16666667]]
  Dimensions: (2, 2)
Test if Ainv * A is identity:
  Ainv * A =
[[1. 0.]
 [0. 1.]]
  A * Ainv =
[[1. 0.]
 [0. 1.]]

Calculation of inverse of B failed, reason:  Singular matrix


#### Exercise 3

This form is equivalent to computing the scalar product of $\vec{v}$ with itself but using the matrix multiplication formalism:
\begin{equation}
    \vec{v}^\mathrm{T}\,\underline{1}\,\vec{v} =
    \left(v_1, v_2, v_3\right)
    \begin{pmatrix}
     1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1
    \end{pmatrix}
    \begin{pmatrix}v_1 \\ v_2 \\ v_3\end{pmatrix} =
    v_1^2 + v_2^2 + v_3^2 =
    \vec{v} \cdot \vec{v}
\end{equation}
The result would be identical without the identity matrix in the center.

Note: In a multidimensional gaussian the same form is used, but with the inverse covariance matrix in the middle
\begin{equation}
    \mathcal{N}(\vec{\mu}, \underline{\Sigma}) \propto
    \exp\left(
        -\frac{1}{2}
        \left(\vec{x}-\vec{\mu}\right)^\mathrm{T}
        \Sigma^{-1}
        \left(\vec{x}-\vec{\mu}\right)
    \right)
\end{equation}
so that in the end the exponential receives a single number as the argument.

See cell below for the computational solution.

In [67]:
# Computational solution for matrix exercise 3
v = np.array([[1], [2], [3]])  # As an example
ID = np.eye(len(v))
res = np.matmul(np.matmul(v.T, ID), v)

v = [1, 2, 3]  # Flat vector only version
comp = np.dot(v, v)

print("Matrix: vT * 1 * v = {}".format(res))  # Gives a (1, 1) matrix
print("Vector: v * v = {}".format(comp))  # Gives a scalar

Matrix: vT * 1 * v = [[14.]]
Vector: v * v = 14
